apiVersion: v2
name: user-service
description: A Helm chart for deploying the User Service microservice on Kubernetes
type: application

version: 0.1.0        # Chart version (for Helm)
appVersion: "1.0.0"   # Your application version (Docker image version)

