{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "user-service.fullname" . }}
  labels:
    release: k8s-monitor
spec:
  selector:
    matchLabels:
      app: {{ include "user-service.name" . }}
  endpoints:
    - port: http
      interval: 15s
{{- end }}

